import type { Metadata } from 'next';

import type { ReactNode } from 'react';

import { ChakraContext } from '@hydra-ipxe/ui/providers';

import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body>
        <ChakraContext>{children}</ChakraContext>
      </body>
    </html>
  );
}
